/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package CaesarPackage;

public class App {    public static void main(String args[]){

//        Scanner sc= new Scanner(System.in);
    String alfabebt="ABCDEFGHIJKLMNOPQRSTUVWXYZ";

    alfabebt=new App().desordenatu(alfabebt);
    System.out.println(alfabebt+" da zure alfabetua");
    //System.out.println("Ondo dago ")
    System.out.println("sartu mezua mesedez:");


    //String mezuGarbia=sc.next();
}

    private String desordenatu(String aldatzeko){
        char[] lista=aldatzeko.toCharArray();
        lista=fisherYates(lista);

        String emaitza="";
        for (int i=0;i<lista.length;i++){
            emaitza=emaitza+lista[i];
        }

        return emaitza;
    }
    //Fisher-Yates shuffle eraginkorra da lista txikiak desordenatzeko, gure kasuan 26 elementuko lista da
    private char[] fisherYates(char[] lista){
        for (int i=0;i<lista.length;i++){
            int auzaz=(int)(Math.random()*25+1);
            swap(lista,i,auzaz);
        }
        return lista;
    }

    private void swap(char[] lista, int a, int b){
        char lag=lista[a];
        lista[a]=lista[b];
        lista[b]=lag;
    }
}
